safe: false
baseurl: /
url: http://blog.jam.net.ve
timezone: America/Caracas
encoding: utf-8

source: .
destination: ./_site
plugins: ./_plugins

future: true
markdown: kramdown
permalink: /:year/:month/:day/:title
highlighter: rouge
excerpt_separator: "<!-- more -->"
paginate: 5
paginate_path: "/page:num"

exclude: ["README.md"]

author:
  name: Jesus Marin
  email: jam@jam.net.ve
  github: jesusangelm
  twitter: jesusangelm
