safe: false
baseurl: /
url: http://blog.jam.net.ve

source: .
destination: ./_site
plugins: ./_plugins

future: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
pygments: true
excerpt_separator: "<!-- more -->"
paginate: 5
paginate_path: "/page:num"

exclude: ["README.md"]

author:
  name: Jesus Marin
  email: jam@jam.net.ve
  github: jesusangelm
  twitter: jesusangelm
